// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2023-03-21 13:01:24.406407 -0500 CDT m=+0.000979126
package util

const SolcVersion = "0.8.19+commit.7dd6d404"

