// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2023-03-29 14:45:21.495606 -0500 CDT m=+0.001203418
package util

const SolcVersion = "0.8.19+commit.7dd6d404"

